import { BotanicalSpecies } from './types';

export const ESPECIO_DATABASE: BotanicalSpecies[] = [
  {
    id: 'bonsai_sabedoria',
    nome: 'Bonsai da Sabedoria',
    emojiSemente: '🌱',
    emojiBroto: '🌿',
    emojiArbusto: '🪴',
    emojiAdulto: '🌳',
    emojiAncia: '🪵',
    categoria: 'Humanas & Direito',
    raridade: 'Comum',
    descricao: 'Um bonsai meticulosamente esculpido que cresce com a leitura atenta de conceitos jurídicos e históricos.',
    comoDesbloquear: 'Estude qualquer assunto de Ciências Humanas ou Direito por mais de 20 minutos.',
    lore: 'Diz a lenda que os antigos magistrados meditavam diante desta planta para obter clareza ao julgar litígios complexos.'
  },
  {
    id: 'espinha_silicio',
    nome: 'Cacto de Silício',
    emojiSemente: '🌵',
    emojiBroto: '🌵',
    emojiArbusto: '🔋',
    emojiAdulto: '🎍',
    emojiAncia: '👾',
    categoria: 'Exatas & Tecnologia',
    raridade: 'Comum',
    descricao: 'Um cacto geométrico brilhante revestido por traços bio-elétricos que se alimenta de cálculos matemáticos e algoritmos.',
    comoDesbloquear: 'Estude Tecnologia, Algoritmos ou Engenharia por mais de 20 minutos.',
    lore: 'Nascido nos desertos de silício artificiais, ele armazena dados estruturados em seus espinhos simétricos.'
  },
  {
    id: 'sakura_calma',
    nome: 'Cerejeira da Paciência',
    emojiSemente: '🌱',
    emojiBroto: '🌿',
    emojiArbusto: '🌸',
    emojiAdulto: '🌺',
    emojiAncia: '🏵️',
    categoria: 'Foco Contínuo',
    raridade: 'Incomum',
    descricao: 'Uma magnífica cerejeira que solta pétalas brilhantes quando os ciclos Pomodoro entram em harmonia estável.',
    comoDesbloquear: 'Complete pelo menos 3 sessões de Pomodoro consecutivas sem pausas atrasadas.',
    lore: 'Cada flor desabrochada representa um estado profundo de foco ininterrupto, exalando um suave perfume de jasmim.'
  },
  {
    id: 'lotus_fogo',
    nome: 'Lótus de Fogo',
    emojiSemente: '🌱',
    emojiBroto: '🌱',
    emojiArbusto: '🌹',
    emojiAdulto: '🔥',
    emojiAncia: '☄️',
    categoria: 'Altíssima Intensidade',
    raridade: 'Rara',
    descricao: 'Uma flor de fogo ardente que floresce apenas em solos altamente energizados por longas horas de dedicação contínua.',
    comoDesbloquear: 'Realize uma única sessão de estudo ininterrupta de pelo menos 90 minutos.',
    lore: 'A lenda diz que suas chamas não queimam a pele, mas sim as dúvidas e inseguranças de quem estuda.'
  },
  {
    id: 'carvalho_ancestral',
    nome: 'Carvalho da Consistência',
    emojiSemente: '🌱',
    emojiBroto: '🌿',
    emojiArbusto: '🌳',
    emojiAdulto: '🌲',
    emojiAncia: '⛰️',
    categoria: 'Streak',
    raridade: 'Rara',
    descricao: 'Um titã de madeira antiga de raízes indestrutíveis que se alimenta puramente da rotina disciplinada diária.',
    comoDesbloquear: 'Mantenha um Streak de estudos de 5 dias seguidos superando todas as metas.',
    lore: 'O carvalho ancestral aguenta qualquer intempérie. Ele ensina que a persistência silenciosa move montanhas.'
  },
  {
    id: 'girassol_solar',
    nome: 'Girassol da Alvorada',
    emojiSemente: '🌱',
    emojiBroto: '🌿',
    emojiArbusto: '🌻',
    emojiAdulto: '☀️',
    emojiAncia: '👑',
    categoria: 'Estudo Matinal',
    raridade: 'Incomum',
    descricao: 'Um girassol majestoso que irradia energia amarela e calor matutino, girando orgulhosamente em direção ao foco do estudante.',
    comoDesbloquear: 'Registre uma sessão de estudos finalizada antes das 11:59 da manhã.',
    lore: 'Esta planta secreta um néctar que cura a fadiga de noites mal dormidas, renovando o ímpeto criativo.'
  },
  {
    id: 'orquidea_lunar',
    nome: 'Orquídea da Penumbra',
    emojiSemente: '🌱',
    emojiBroto: '🌿',
    emojiArbusto: '🪻',
    emojiAdulto: '🌌',
    emojiAncia: '🔮',
    categoria: 'Estudo Noturno',
    raridade: 'Incomum',
    descricao: 'Uma flor azul-escura luminescente que absorve a luz das estrelas e emite um brilho sereno no silêncio da noite.',
    comoDesbloquear: 'Registre uma sessão de estudos iniciada após as 20:00 da noite.',
    lore: 'Guardiã daqueles que preferem o silêncio da madrugada. Suas flores reluzem mais conforme a escuridão aumenta.'
  },
  {
    id: 'cristal_sakura',
    nome: 'Flor de Cristal Teórico',
    emojiSemente: '💎',
    emojiBroto: '❄️',
    emojiArbusto: '💠',
    emojiAdulto: '🔮',
    emojiAncia: '🌌',
    categoria: 'Metódica',
    raridade: 'Lendária',
    descricao: 'Uma flora cristalizada prismática que deforma a luz solar em espectros coloridos de autoconfiança intelectual.',
    comoDesbloquear: 'Alcance um total de pelo menos 100 perguntas resolvidas no painel de Questões.',
    lore: 'Uma verdadeira maravilha da biologia conceitual. Suas pétalas imortais cristalizam ideias antes impossíveis de fixar na mente.'
  }
];
